apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello1
  template:
    metadata:
      labels:
        app: hello1
    spec:
      containers:
      - name: hello1
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello1
spec:
  selector:
    app: hello1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
